class Reader:
    def __init__(self, buffer: bytes, endian: str = 'big'):
        self.buffer = buffer
        self.endian = endian
        self.i = 0

    def read(self, length: int = 1): ...

    def readUInteger(self, length: int = 1) -> int: ...

    def readInteger(self, length: int = 1) -> int: ...

    def readUInt64(self) -> int: ...

    def readInt64(self) -> int: ...

    def readFloat(self) -> float: ...

    def readUInt32(self) -> int: ...

    def readInt32(self) -> int: ...

    def readNUInt16(self) -> float: ...

    def readUInt16(self) -> int: ...

    def readNInt16(self) -> float: ...

    def readInt16(self) -> int: ...

    def readUInt8(self) -> int: ...

    def readInt8(self) -> int: ...

    def readBool(self) -> bool: ...

    readUInt = readUInteger
    readInt = readInteger

    readULong = readUInt64
    readLong = readInt64

    readNUShort = readNUInt16
    readNShort = readNInt16

    readUShort = readUInt16
    readShort = readInt16

    readUByte = readUInt8
    readByte = readInt8

    def readChar(self, length: int = 1) -> str: ...

    def readString(self) -> str: ...

    def tell(self) -> int: ...
