class Writer:
    def __init__(self, endian: str = 'big'):
        self.endian = endian
        self.buffer = b''

    def write(self, data: bytes) -> None: ...

    def writeUInteger(self, integer: int, length: int = 1) -> None: ...

    def writeInteger(self, integer: int, length: int = 1) -> None: ...

    def writeUInt64(self, integer: int) -> None: ...

    def writeInt64(self, integer: int) -> None: ...

    def writeFloat(self, floating: float) -> None: ...

    def writeUInt32(self, integer: int) -> None: ...

    def writeInt32(self, integer: int) -> None: ...

    def writeNUInt16(self, integer: int) -> None: ...

    def writeUInt16(self, integer: int) -> None: ...

    def writeNInt16(self, integer: int) -> None: ...

    def writeInt16(self, integer: int) -> None: ...

    def writeUInt8(self, integer: int) -> None: ...

    def writeInt8(self, integer: int) -> None: ...

    def writeBool(self, boolean: bool) -> None: ...

    writeUInt = writeUInteger
    writeInt = writeInteger

    writeULong = writeUInt64
    writeLong = writeInt64

    writeNUShort = writeNUInt16
    writeNShort = writeNInt16

    writeUShort = writeUInt16
    writeShort = writeInt16

    writeUByte = writeUInt8
    writeByte = writeInt8

    def writeChar(self, string: str) -> None: ...

    def writeString(self, string: str) -> None: ...
